global_frame: map
rolling_window: true
track_unknown_space: true
static_map: true

plugins:
 - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
 - {name: static type: "costmap_2d::StaticLayer"}
 - {name: inflation, type: "costmap_2d::InflationLayer"}

